# Generated by Django 4.1.7 on 2023-03-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.IntegerField()),
                ("brand", models.CharField(max_length=250)),
                ("title", models.CharField(max_length=250)),
            ],
        ),
    ]
